In [1]:
#outliers

In [2]:
import pandas as pd
import numpy as np
pd.options.display.max_columns=None
pd.options.display.max_rows=None

In [3]:
df = pd.read_csv('sample_train_good_40k.csv')
df.head()

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,88744,0,Cash loans,F,N,Y,2,405000.0,1398901.5,95377.5,1291500.0,Unaccompanied,Working,Secondary / secondary special,Married,Rented apartment,0.006671,-12893,-3494,-3165.0,-218,NaN,1,1,0,1,0,0,NaN,4.0,2,2,THURSDAY,18,0,0,0,0,0,0,Self-employed,NaN,0.569841,NaN,0.0464,0.1576,0.9816,NaN,NaN,0.0,0.0345,0.0833,NaN,0.1858,NaN,0.0353,NaN,0.1247,0.0473,0.1636,0.9816,NaN,NaN,0.0,0.0345,0.0833,NaN,0.1901,NaN,0.0368,NaN,0.132,0.0468,0.1576,0.9816,NaN,NaN,0.0,0.0345,0.0833,NaN,0.1891,NaN,0.0359,NaN,0.1273,NaN,block of flats,0.0618,Panel,No,0.0,0.0,0.0,0.0,-1783.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,200904,0,Cash loans,M,Y,N,0,225000.0,785398.5,54661.5,702000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.019101,-17858,-584,-8519.0,-1417,6.0,1,1,0,1,0,0,Drivers,2.0,2,2,FRIDAY,13,0,0,0,0,1,1,Business Entity Type 3,NaN,0.724698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-76.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
2,305523,0,Revolving loans,F,N,Y,1,90000.0,270000.0,13500.0,270000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.018209,-15342,-1941,-2988.0,-4324,NaN,1,1,0,1,1,0,High skill tech staff,3.0,3,3,MONDAY,14,0,0,0,0,0,0,Business Entity Type 3,0.803825,0.555394,0.753067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-142.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
3,12704,0,Cash loans,M,N,N,2,90000.0,288873.0,19435.5,238500.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,With parents,0.002134,-8756,-822,-1338.0,-1436,NaN,1,1,0,1,0,0,Security staff,4.0,3,3,SATURDAY,11,0,0,0,0,1,1,Trade: type 7,NaN,0.553054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,270115,0,Cash loans,M,N,Y,0,90000.0,254700.0,24939.0,225000.0,Unaccompanied,Pensioner,Lower secondary,Married,House / apartment,0.022800,-22235,365243,-9093.0,-4980,NaN,1,0,0,1,0,0,NaN,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,XNA,NaN,0.262258,0.329655,0.0722,0.0709,0.9876,0.83,0.0149,0.0,0.2069,0.1667,0.0,0.0509,0.0588,0.0727,0.0,0.0000,0.0735,0.0736,0.9876,0.8367,0.015,0.0,0.2069,0.1667,0.0,0.0521,0.0643,0.0757,0.0,0.000,0.0729,0.0709,0.9876,0.8323,0.015,0.0,0.2069,0.1667,0.0,0.0518,0.0599,0.0740,0.0,0.0000,reg oper account,block of flats,0.0653,"Stone, brick",No,1.0,1.0,1.0,1.0,-426.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [4]:
ds=df[['CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'HOUR_APPR_PROCESS_START', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'YEARS_BUILD_AVG', 'ELEVATORS_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'APARTMENTS_MODE', 'YEARS_BUILD_MODE', 'ELEVATORS_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LIVINGAREA_MODE', 'APARTMENTS_MEDI', 'YEARS_BUILD_MEDI', 'ELEVATORS_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_YEAR']]

In [5]:
ds.shape

(40000, 42)

In [6]:
q1=ds.quantile(0.25)
q3=ds.quantile(0.75)
iqr=q3-q1
ll=q1-iqr*10
ul=q3+iqr*10

In [7]:
do=ds[~((ds<ll)|(ds>ul)).any(axis=1)]

In [8]:
do.shape

(24794, 42)

In [9]:
(((ds<ll)|(ds>ul)).sum(axis=0)/ds.shape[0])*100

CNT_CHILDREN                   0.0025
AMT_INCOME_TOTAL               0.0950
AMT_CREDIT                     0.0000
AMT_GOODS_PRICE                0.0000
REGION_POPULATION_RELATIVE     0.0000
DAYS_BIRTH                     0.0000
DAYS_EMPLOYED                 18.0800
DAYS_REGISTRATION              0.0000
DAYS_ID_PUBLISH                0.0000
OWN_CAR_AGE                    0.0000
HOUR_APPR_PROCESS_START        0.0000
EXT_SOURCE_1                   0.0000
EXT_SOURCE_2                   0.0000
EXT_SOURCE_3                   0.0000
APARTMENTS_AVG                 0.0000
YEARS_BUILD_AVG                0.0000
ELEVATORS_AVG                  0.0000
FLOORSMAX_AVG                  0.0000
FLOORSMIN_AVG                  0.0000
LIVINGAPARTMENTS_AVG           0.0325
LIVINGAREA_AVG                 0.0525
APARTMENTS_MODE                0.0000
YEARS_BUILD_MODE               0.0000
ELEVATORS_MODE                 0.0000
FLOORSMAX_MODE                 0.0000
FLOORSMIN_MODE                 0.0000
LIVINGAREA_MODE                0.0575
APARTMENTS_MEDI                0.0000
YEARS_BUILD_MEDI               0.0000
ELEVATORS_MEDI                 0.0000
FLOORSMAX_MEDI                 0.0000
FLOORSMIN_MEDI                 0.0000
LIVINGAPARTMENTS_MEDI          0.0325
LIVINGAREA_MEDI                0.0525
TOTALAREA_MODE                 0.0625
OBS_30_CNT_SOCIAL_CIRCLE       0.0200
DEF_30_CNT_SOCIAL_CIRCLE      11.4050
OBS_60_CNT_SOCIAL_CIRCLE       0.0200
DEF_60_CNT_SOCIAL_CIRCLE       8.4150
DAYS_LAST_PHONE_CHANGE         0.0000
AMT_REQ_CREDIT_BUREAU_MON     14.0650
AMT_REQ_CREDIT_BUREAU_YEAR     0.0000
dtype: float64